
configMapGenerator:
  - name: example-configmap
    literals:
      - ENV=local
  - behavior: replace
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

#namespace: test
#commonAnnotations:
#  commanno: jjaa
commonLabels:
  app: py-api
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

vars:
  - name: SVC_NAME
    objref:
      kind: Ingress
      name: py-api
      apiVersion: networking.k8s.io/v1beta1
