#configMapGenerator:
#  - name: example-configmap
#    literals:
#      - ENV=dev
#  - behavior: merge
#generatorOptions:
#  disableNameSuffixHash: true
#  labels:
#    type: generated
#  annotations:
#    note: generated


bases:
  - ../../base
#resources:
#  - ../../base/kustomization.yaml

patchesStrategicMerge:
  - deployment.yaml
#  - ingress.yaml

namePrefix: dev-

patchesJson6902:
  - path: hostname-patch.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: py-api
  - path: configmap-patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: example-configmap
